Overhaul of in-app documentation and addition of font coloring.
tulir/gomuks pull request #306
Opened 2021-08-18 22:21 UTC by yunginnanet

- `/html` I've implemented a very clunky but functional and safe example of custom HTML formatting in messages. It allows foreground and background text colors to be chosen by the user. This renders perfectly in Element  in messages and emotes; **despite Element not allowing users to use color text in their client besides rainbows.**.

- `in app documentation` As someone with a disability _(I am a religious GNU nano user)_ I found the lack of documentation for any keyboard shortcuts **pretty spooky.** I've upgraded and made some minor changes to the in-app documentation that I think would help keep someone interested in using this client.

2021-08-26 22:29 UTC, Ulexus commented on ui/commands.go
> +func cmdPornhub(cmd *Command) {
Is this seriously some common term for doing color overrides?

2021-08-27 06:24 UTC, yunginnanet commented on ui/commands.go
> +func cmdPornhub(cmd *Command) {
(That wasn't supposed to be in this PR)

2021-08-28 04:39 UTC, yunginnanet reviewed
Fixed

2021-09-07 23:03 UTC, tulir requested changes

2021-09-07 23:03 UTC, tulir commented on ui/commands.go
> +	go cmd.Room.SendMessageHTML(msgtype, htmlStrip(htmlInput), htmlBody)
Sending HTML is already possible (`/toggle html` and also `/toggle markdown`), but I guess it might be useful to have an explicit HTML-only command instead of having to toggle things back and forth (relatedly, explicit `/plain` and `/markdown` commands might also be useful).

Doesn't need sanitization though, that's the recipient's responsibility (`htmlSanitize` and the bluemonday dep should also be removed)

```suggestion
	go cmd.Room.SendMessageHTML(msgtype, format.HTMLToText(cmd.RawArgs), cmd.RawArgs)
```

2021-09-07 23:03 UTC, tulir commented on ui/commands.go
> +func cmdHtmlme(cmd *Command) {
This should be `cmdHTMLMe` (and all the other instances of `Html` should also be uppercased)

2021-09-07 23:03 UTC, tulir commented on ui/commands.go
> +		cmd.Reply("Usage: /html <message>")
Currently usage shows `/html` even when using `/htmlme`

```suggestion
		cmd.Reply("Usage: /%s <message>", cmd.Command)
```

2021-09-07 23:03 UTC, tulir commented on gomuks.go
> +	return "v0.2.3a"
Version number is only changed for new releases (including git commit info for non-release builds might be a good idea in the future though)

```suggestion
	return "v0.2.3"
```

2021-09-07 23:03 UTC, tulir commented on ui/help-modal.go
> +   e.g: '/html <font color="#FFF" data-mx-bg-color="#000">white on black</font>'
These aren't related to font tags nor Element

```suggestion
/html <message>      - Send a raw HTML-formatted text message.
/htmlme <message>    - Same as /html, but send an emote message.
```

2021-09-07 23:03 UTC, tulir commented on ui/help-modal.go
> +
```suggestion
/import <file> - Import encryption keys. You should clear cache afterwards
                 to retry decrypting old messages.
```

2021-11-10 01:09 UTC, yunginnanet commented
Oh wow, I actually somehow never saw you respond to this PR. My apologies. 

I'll take a look at your requested changes, as I do think your users would benefit from the documentation that I added. Ignore my recent commits (I had given up on this PR as I somehow missed all the notifications).

 I'll likely tear this PR down and make a fresh one. Thank you.

2021-11-10 08:04 UTC, closed without merging